# Generated by Django 4.2.5 on 2023-09-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
