# Generated by Django 4.2.5 on 2023-09-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calApp', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='def.png', max_length=20, upload_to='prof_pic/'),
        ),
    ]
