# Generated by Django 4.2.5 on 2023-09-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calApp', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relagion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Buddha', 'Buddha'), ('Christan', 'Christan')], default='Hindu', max_length=20),
        ),
    ]
